insert into rmt_device (id,description,device_type) values (1,'Steel HR 001',1);
insert into rmt_device (id,description,device_type) values (2,'Steel HR 002',1);
insert into rmt_device (id,description,device_type) values (3,'Steel HR 003',1);
insert into rmt_device (id,description,device_type) values (4,'Steel HR 004',1);
insert into rmt_device (id,description,device_type) values (5,'Steel HR 005',1);
insert into rmt_device (id,description,device_type) values (6,'Steel HR 006',1);
insert into rmt_device (id,description,device_type) values (7,'Steel HR 007',1);
insert into rmt_device (id,description,device_type) values (8,'Steel HR 008',1);
insert into rmt_device (id,description,device_type) values (9,'Steel HR 011',1);
insert into rmt_device (id,description,device_type) values (10,'Steel HR 012',1);
insert into rmt_device (id,description,device_type) values (11,'Steel HR 013',1);
insert into rmt_device (id,description,device_type) values (12,'Steel HR 014',1);
insert into rmt_device (id,description,device_type) values (13,'Steel HR 015',1);
insert into rmt_device (id,description,device_type) values (14,'Steel HR 016',1);
insert into rmt_device (id,description,device_type) values (15,'Steel HR 017',1);
insert into rmt_device (id,description,device_type) values (16,'Steel HR 018',1);
insert into rmt_device (id,description,device_type) values (17,'Steel HR 019',1);
insert into rmt_device (id,description,device_type) values (18,'Steel HR 020',1);
insert into rmt_device (id,description,device_type) values (19,'BPM+ 001',2);
insert into rmt_device (id,description,device_type) values (20,'BPM+ 002',2);
insert into rmt_device (id,description,device_type) values (21,'BPM+ 003',2);
insert into rmt_device (id,description,device_type) values (22,'BPM+ 004',2);
insert into rmt_device (id,description,device_type) values (23,'BPM+ 005',2);
insert into rmt_device (id,description,device_type) values (24,'BPM+ 006',2);
insert into rmt_device (id,description,device_type) values (25,'BPM+ 007',2);
insert into rmt_device (id,description,device_type) values (26,'BPM+ 008',2);
insert into rmt_device (id,description,device_type) values (27,'BPM+ 011',2);
insert into rmt_device (id,description,device_type) values (28,'BPM+ 012',2);
insert into rmt_device (id,description,device_type) values (29,'BPM+ 013',2);
insert into rmt_device (id,description,device_type) values (30,'BPM+ 014',2);
insert into rmt_device (id,description,device_type) values (31,'BPM+ 015',2);
insert into rmt_device (id,description,device_type) values (32,'BPM+ 016',2);
insert into rmt_device (id,description,device_type) values (33,'BPM+ 017',2);
insert into rmt_device (id,description,device_type) values (34,'BPM+ 018',2);
insert into rmt_device (id,description,device_type) values (35,'BPM+ 019',2);
insert into rmt_device (id,description,device_type) values (36,'BPM+ 020',2);
insert into rmt_device (id,description,device_type) values (37,'BPM+ 021',2);
insert into rmt_device (id,description,device_type) values (38,'BPM 999',5);
insert into rmt_device (id,description,device_type) values (39,'Body+ 001',3);
insert into rmt_device (id,description,device_type) values (40,'Body+ 002',3);
insert into rmt_device (id,description,device_type) values (41,'Body+ 003',3);
insert into rmt_device (id,description,device_type) values (42,'Body+ 004',3);
insert into rmt_device (id,description,device_type) values (43,'Body+ 005',3);
insert into rmt_device (id,description,device_type) values (44,'Body+ 006',3);
insert into rmt_device (id,description,device_type) values (45,'Body+ 007',3);
insert into rmt_device (id,description,device_type) values (46,'Body+ 008',3);
insert into rmt_device (id,description,device_type) values (47,'Body+ 009',3);
insert into rmt_device (id,description,device_type) values (48,'Body+ 011',3);
insert into rmt_device (id,description,device_type) values (49,'Body+ 012',3);
insert into rmt_device (id,description,device_type) values (50,'Body+ 013',3);
insert into rmt_device (id,description,device_type) values (51,'Body+ 014',3);
insert into rmt_device (id,description,device_type) values (52,'Body+ 015',3);
insert into rmt_device (id,description,device_type) values (53,'Body+ 016',3);
insert into rmt_device (id,description,device_type) values (54,'Body+ 017',3);
insert into rmt_device (id,description,device_type) values (55,'Body+ 018',3);
insert into rmt_device (id,description,device_type) values (56,'Body+ 019',3);
insert into rmt_device (id,description,device_type) values (57,'Body+ 020',3);
insert into rmt_device (id,description,device_type) values (58,'Samsung Galaxy J5 001',4);
insert into rmt_device (id,description,device_type) values (59,'Samsung Galaxy J5 002',4);
insert into rmt_device (id,description,device_type) values (60,'Samsung Galaxy J5 003',4);
insert into rmt_device (id,description,device_type) values (61,'Samsung Galaxy J5 004',4);
insert into rmt_device (id,description,device_type) values (62,'Samsung Galaxy J5 005',4);
insert into rmt_device (id,description,device_type) values (63,'Samsung Galaxy J5 006',4);
insert into rmt_device (id,description,device_type) values (64,'Samsung Galaxy J5 007',4);
insert into rmt_device (id,description,device_type) values (65,'Samsung Galaxy J5 008',4);
insert into rmt_device (id,description,device_type) values (66,'Samsung Galaxy J5 009',4);
insert into rmt_device (id,description,device_type) values (67,'Samsung Galaxy J5 010',4);
insert into rmt_device (id,description,device_type) values (68,'Samsung Galaxy J5 011',4);
insert into rmt_device (id,description,device_type) values (69,'Samsung Galaxy J5 012',4);
insert into rmt_device (id,description,device_type) values (70,'Samsung Galaxy J5 013',4);
insert into rmt_device (id,description,device_type) values (71,'Samsung Galaxy J5 014',4);
insert into rmt_device (id,description,device_type) values (72,'Samsung Galaxy J5 015',4);
insert into rmt_device (id,description,device_type) values (73,'Samsung Galaxy J5 016',4);
insert into rmt_device (id,description,device_type) values (74,'Samsung Galaxy J5 017',4);
insert into rmt_device (id,description,device_type) values (75,'Samsung Galaxy J5 018',4);
insert into rmt_device (id,description,device_type) values (76,'Samsung Galaxy J5 019',4);
insert into rmt_device (id,description,device_type) values (77,'Samsung Galaxy J5 020',4);
insert into rmt_device (id,description,device_type) values (78,'Nonin3150_502726385',7);
insert into rmt_device (id,description,device_type) values (79,'Nonin3150_502774793',7);
insert into rmt_device (id,description,device_type) values (80,'Nonin3150_502726383',7);
insert into rmt_device (id,description,device_type) values (81,'Nonin3150_502726398',7);
insert into rmt_device (id,description,device_type) values (82,'Nonin3150_502691994',7);
insert into rmt_device (id,description,device_type) values (83,'Nonin3150_502691989',7);
insert into rmt_device (id,description,device_type) values (84,'Nonin3150_502692370',7);
insert into rmt_device (id,description,device_type) values (85,'Nonin3150_502692018',7);
insert into rmt_device (id,description,device_type) values (86,'Nonin3150_502731374',7);
insert into rmt_device (id,description,device_type) values (87,'Nonin3150_502692025',7);

