insert into rmt_measure_type (id,description,unit) values (1,'Heart Rate','bpm');
insert into rmt_measure_type (id,description,unit) values (2,'Steps','#');
insert into rmt_measure_type (id,description,unit) values (3,'Distance','m');
insert into rmt_measure_type (id,description,unit) values (4,'Calories','kcal');
insert into rmt_measure_type (id,description,unit) values (5,'Sleep State','#');
insert into rmt_measure_type (id,description,unit) values (6,'Soft','s');
insert into rmt_measure_type (id,description,unit) values (7,'Moderate','s');
insert into rmt_measure_type (id,description,unit) values (8,'Intense','s');
insert into rmt_measure_type (id,description,unit) values (9,'Total Calories','kcal');
insert into rmt_measure_type (id,description,unit) values (10,'Metcumul','?');
insert into rmt_measure_type (id,description,unit) values (11,'Intensity','?');
insert into rmt_measure_type (id,description,unit) values (12,'HR Average','bpm');
insert into rmt_measure_type (id,description,unit) values (13,'HR Min','bpm');
insert into rmt_measure_type (id,description,unit) values (14,'HR Max','bpm');
insert into rmt_measure_type (id,description,unit) values (15,'HR Zone 0','?');
insert into rmt_measure_type (id,description,unit) values (16,'HR Zone 1','?');
insert into rmt_measure_type (id,description,unit) values (17,'HR Zone 2','?');
insert into rmt_measure_type (id,description,unit) values (18,'HR Zone 3','?');
insert into rmt_measure_type (id,description,unit) values (19,'Diastolic Blood Pressure','mmHg');
insert into rmt_measure_type (id,description,unit) values (20,'Systolic Blood Pressure','mmHg');
insert into rmt_measure_type (id,description,unit) values (21,'Weight','kg');
insert into rmt_measure_type (id,description,unit) values (22,'Fat Free Mass','kg');
insert into rmt_measure_type (id,description,unit) values (23,'Fat Ratio','%');
insert into rmt_measure_type (id,description,unit) values (24,'Fat Mass','kg');
insert into rmt_measure_type (id,description,unit) values (25,'Muscle Mass','kg');
insert into rmt_measure_type (id,description,unit) values (26,'Hydration','%');
insert into rmt_measure_type (id,description,unit) values (27,'Bone Mass','kg');
insert into rmt_measure_type (id,description,unit) values (28,'Pulse Wave Velocity','m/s');
insert into rmt_measure_type (id,description,unit) values (29,'Height','m');
insert into rmt_measure_type (id,description,unit) values (30,'Peripheral Oxygen Saturation','%');