insert into rmt_measure_type_pt (measure_type,description) values (1,'Frequência Cardíaca');
insert into rmt_measure_type_pt (measure_type,description) values (2,'Passos');
insert into rmt_measure_type_pt (measure_type,description) values (3,'Distância');
insert into rmt_measure_type_pt (measure_type,description) values (4,'Calorias');
insert into rmt_measure_type_pt (measure_type,description) values (5,'Estado de sono');
insert into rmt_measure_type_pt (measure_type,description) values (6,'Leve');
insert into rmt_measure_type_pt (measure_type,description) values (7,'Moderada');
insert into rmt_measure_type_pt (measure_type,description) values (8,'Intensa');
insert into rmt_measure_type_pt (measure_type,description) values (9,'Total de calorias');
insert into rmt_measure_type_pt (measure_type,description) values (10,'Metcumul');
insert into rmt_measure_type_pt (measure_type,description) values (11,'Intensidade');
insert into rmt_measure_type_pt (measure_type,description) values (12,'Frequência Cardíaca Média');
insert into rmt_measure_type_pt (measure_type,description) values (13,'Frequência Cardíaca Mínima');
insert into rmt_measure_type_pt (measure_type,description) values (14,'Frequência Cardíaca Máxima');
insert into rmt_measure_type_pt (measure_type,description) values (15,'Zona 0 Frequência Cardíaca');
insert into rmt_measure_type_pt (measure_type,description) values (16,'Zona 1 Frequência Cardíaca');
insert into rmt_measure_type_pt (measure_type,description) values (17,'Zona 2 Frequência Cardíaca');
insert into rmt_measure_type_pt (measure_type,description) values (18,'Zona 3 Frequência Cardíaca');
insert into rmt_measure_type_pt (measure_type,description) values (19,'Tensão Arterial Diastólica');
insert into rmt_measure_type_pt (measure_type,description) values (20,'Tensão Arterial Sistólica');
insert into rmt_measure_type_pt (measure_type,description) values (21,'Peso');
insert into rmt_measure_type_pt (measure_type,description) values (22,'Massa magra');
insert into rmt_measure_type_pt (measure_type,description) values (23,'Rácio de gordura');
insert into rmt_measure_type_pt (measure_type,description) values (24,'Massa gorda');
insert into rmt_measure_type_pt (measure_type,description) values (25,'Massa muscular');
insert into rmt_measure_type_pt (measure_type,description) values (26,'Percentagem de água corporal');
insert into rmt_measure_type_pt (measure_type,description) values (27,'Massa óssea');
insert into rmt_measure_type_pt (measure_type,description) values (28,'Velocidade de pulso');
insert into rmt_measure_type_pt (measure_type,description) values (29,'Altura');
insert into rmt_measure_type_pt (measure_type,description) values (30,'Saturaçao Periférica de Oxigénio');